### ISSUE TITLE
Is the game environment reset after losing a life in training?

### ISSUE THREAD

**Issue by boranzhao** [deepmind/dqn#3]
Hi guys, 

After reading the codes, I am aware of that losing a life is regarded as the end of an episode in training, while game over (i.e. losing all lives) is regarded as the end in testing (or evaluation). Please correct me if I am wrong. However, I am still confused about what happens to the game environment after losing a life **in training**.  In the code (Lines 90-92 of train_agent.lua),  two options are listed, i.e. `game_env:nextRandomGame() `and `game_env:newGame()`.  Does the former refer to resetting the environment for next episode, and the latter refer to directly starting the next episode without resetting? 

I asked this question because I met a problem in training and testing my agent. Currently, I reset my game environment after losing a life in training.  When I tested my agent with a greedy policy, i.e. for playing,  I keep the game running until it is over. However, the game will get stuck after losing a life.  I was wondering whether this is related to resetting the environment after losing a life in training. 

Thanks.

**Comment by GeorgOstrovski** [comment]
Hello, 

The difference between nextRandomGame() and newGame() is whether or not random no-ops are inserted. DQN inserts a number of no-op actions at the beginning of each episode, this number being drawn uniformly randomly from (0, 1, ... , 30) each time. In the code you are pointing to, this happens conditionally on wether the parameter "random_starts" is positive or not.

**Comment by GeorgOstrovski** [comment]
You can see the implementations of these functions [here](https://github.com/deepmind/alewrap/blob/master/alewrap/GameEnvironment.lua#L146)

**Comment by boranzhao** [comment]
@GeorgOstrovski  Thanks for the explanation! I just want to double check one more thing. I found that  losing a life is regarded as the end of an episode in training, while game over (i.e. losing all lives) is regarded as the end in testing (or evaluation). However, during training, do you reset the episode after a life is lost?

**Comment by GeorgOstrovski** [comment]
Not sure what you mean by 'reset the episode'? If you mean, completely reset the game (i.e. jump to initial state with full lives count) than the answer is no, we don't do that.

During training, `terminal=True` would be received when a life is lost (because we pass `training=True` to `game_env:step()` [here](https://github.com/deepmind/dqn/blob/master/dqn/train_agent.lua#L87). Tracing through the code, this leads to a call to `newGame()` or `nextRandomGame()`. If you look at the [ALE code for these functions](https://github.com/deepmind/alewrap/blob/master/alewrap/GameEnvironment.lua#L131), these don't 'hard-reset' the underlying environment, they just keep on playing it. 

So in both training & evaluation, a loss of a life has the same consequences from the environment's point of view, it's just the agent that interprets these differently (as an end of episode or not).

**Comment by boranzhao** [comment]
Thanks for the detailed explanation. Yes, when I said "reset the episode", I meant completely resetting the game.
